project:
  type: website
  output-dir: _site

website:
  title: "BirdNET Observations"
  navbar:
    left:
      - text: "Last Hour"
        file: last_hour.qmd
      - text: "Day Summary"
        file: day_summary.qmd
      - text: "Week Summary"
        file: week_summary.qmd
      - text: "Stats"
        file: stats.qmd

format:
  html:
    theme: cosmo
    toc: true
    include-after-body: refresh.js